#!/bin/sh
### BEGIN INIT INFO
# Provides:          gdomoticz
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GDomoticz
# Description:       GDomoticz
### END INIT INFO

case "$1" in
  start)
    /bin/su - pi -c "/apps/gdomoticz/start.sh"
    ;;
  stop)
    /bin/su - pi -c "/apps/gdomoticz/stop.sh"
    ;;
  *)
    echo "Usage: /etc/init.d/gdomoticz {start|stop}"
    exit 1
    ;;
esac

exit 0
